FROM node:20-alpine

WORKDIR /app

COPY services/frontend/package.json .
COPY services/frontend/pnpm-lock.yaml .

RUN npm install -g pnpm && pnpm install

COPY services/frontend/ .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]