FROM golang:1.22-alpine

WORKDIR /app

COPY services/backend/go.mod .
COPY services/backend/go.sum .

RUN go mod download

COPY services/backend/ .

RUN go build -o backend .

EXPOSE 8081

CMD ["./backend"]